== Configuration

A list of constants that allows you to change the behaviour of Dolibarr. These settings are not configurable in the user interface.

WARNING: This page contains the list of some advanced development parameters. In most cases, it is parameters for internal usage, development, external modules, features in development not stable or that may lead to security risk. For standard usage of Dolibarr, such parameters SHOULD NOT be used. All experimental options are NOT supported. They may be removed in a future, modified at any version and break stability of your application.

=== Global Options

link:/home/configuration/MAIN_LANGUAGES_ALLOWED[MAIN_LANGUAGES_ALLOWED] > Is a list of languages without spaces, example : fr_FR,en_US,de_DE,it_IT If defined, only those languages will appear in combos. > V11.0

=== Interface 

link:/home/configuration/MAIN_CHECKBOX_LEFT_COLUMN[MAIN_CHECKBOX_LEFT_COLUMN] > Third party interface Move checkbox column as first column on Thirdparty list. > V17.0

