== Set Languages
:icons: font

Languages can be set in the following areas: +


=== Global language setting

In the language settings, you can set the Default Language. By default it is set to "Auto Detect".

ifdef::env-github[]
:tip-caption: :bulb:
endif::[]

[TIP]
Home > Setup > Display > **Language and presentation** 

Activating multilanguage option will allow you to set the preferred language of customers, to print their Invoice/Proposal/Order in their specific language. Product translations are also available.

By default all language of which a translation exists in Dolibarr are available. For many companies this is too much as they only want to support a few languages. To limit the number of available languages make the following setting:



=== User language setting

The user language Display Setup is set in the user display menu.

ifdef::env-github[]
:tip-caption: :bulb:
endif::[]

[TIP]
Home > Users & Groups > List of Users > **User Display Setup**

Modify: Enable **Use personal value** Select desired option  


Their is a second entry to set a user language, but this refers to the **language the user speak** not the language of the interface

ifdef::env-github[]
:tip-caption: :bulb:
endif::[]

[TIP]
Home -> Users & Groups > List of Users > **User** > Default language

=== Product translations

When their is a requirement to make proposals and invoices in different languages activate the multilanguage option. 

ifdef::env-github[]
:tip-caption: :bulb:
endif::[]

[TIP]
Home > Setup > Display > **Language and presentation** 

Next move to a product page


